const POLICY={missing_order:{id:'P-01',text:'费用付款记录必须包含订单编号；缺失时提交人工复核。'},missing_invoice:{id:'P-01',text:'费用付款记录必须包含发票号；缺失时提交人工复核。'},duplicate_invoice:{id:'P-02',text:'同一发票号重复，应标记风险并由人工核对。'},over_limit:{id:'P-03',text:'单笔金额超过演示阈值10000元时转人工审核。'},invalid_amount:{id:null,text:'演示制度无充分依据；金额字段需人工核对。'}};
const NAMES={missing_order:'订单编号缺失',missing_invoice:'发票号缺失',duplicate_invoice:'发票号重复',over_limit:'超过演示金额阈值',invalid_amount:'金额无效'};
const FIELDS=['payment_id','order_id','invoice_id','amount','vendor'];
let last=null;
function parseCSV(source){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'&&quoted&&source[i+1]==='"'){field+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(field);field='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.length))rows.push(row);row=[];field='';continue}field+=c}if(quoted)throw Error('CSV 引号未闭合');row.push(field);if(row.some(x=>x.length))rows.push(row);if(!rows.length)throw Error('CSV 为空');const headers=rows.shift().map(x=>x.trim().replace(/^\ufeff/,''));const missing=FIELDS.filter(k=>!headers.includes(k));if(missing.length)throw Error('缺少字段：'+missing.join('、'));if(rows.length>5000)throw Error('最多处理5000条');return rows.map((cells,i)=>{if(cells.length!==headers.length)throw Error('第'+(i+2)+'行字段数量不一致');return Object.fromEntries(headers.map((h,j)=>[h,cells[j]]))})}
function analyze(rows){const seen=new Set(),findings=[];for(const row of rows){const flags=[];if(!String(row.order_id||'').trim())flags.push('missing_order');const invoice=String(row.invoice_id||'').trim();if(!invoice)flags.push('missing_invoice');else if(seen.has(invoice))flags.push('duplicate_invoice');if(invoice)seen.add(invoice);const raw=String(row.amount??'').trim(),amount=Number(raw);if(!raw||!Number.isFinite(amount)||amount<0)flags.push('invalid_amount');else if(amount>10000)flags.push('over_limit');if(flags.length){const policy=POLICY[flags[0]];findings.push({payment_id:row.payment_id,flags,amount:row.amount,citation:policy.id?'data/demo_policy.json#'+policy.id:null,excerpt:policy.text,review_status:'pending_human_review'})}}return {input_count:rows.length,findings,approval:'pending_human_review',method:'browser rule demonstration'}}
function status(message,type='neutral'){const el=document.querySelector('#status');el.textContent=message;el.className='status '+type}
function render(data){last=data;document.querySelector('#download').disabled=false;document.querySelector('#metrics').innerHTML='<div><strong>'+data.input_count+'</strong><span>输入记录</span></div><div><strong>'+data.findings.length+'</strong><span>待复核</span></div><div><strong>人工</strong><span>审批状态</span></div>';const area=document.querySelector('#results');area.replaceChildren();area.className='scroll-results';if(!data.findings.length){area.textContent='未发现当前规则定义的异常，付款仍须人工审核。';return}for(const f of data.findings){const block=document.createElement('div');block.className='finding';const head=document.createElement('strong');head.textContent=f.payment_id+' · '+f.flags.map(x=>NAMES[x]).join('、');const why=document.createElement('p');why.textContent=f.excerpt;const foot=document.createElement('small');foot.textContent=(f.citation||'无可引用条款')+' · 待人工复核';block.append(head,why,foot);area.append(block)}}
document.querySelector('#sample').addEventListener('click',async()=>{try{const response=await fetch('./data/holdout_20.json');if(!response.ok)throw Error('案例加载失败');const data=analyze(await response.json());render(data);status('已完成20条记录的本地检查。','success')}catch(e){status(e.message,'error')}});
document.querySelector('#upload').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;const rows=parseCSV(await file.text());render(analyze(rows));status('已检查 '+rows.length+' 条记录。','success')}catch(error){status(error.message,'error')}});
document.querySelector('#download').addEventListener('click',()=>{if(!last)return;const url=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='expense-review-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
fetch('./data/chat_output_trace.json').then(r=>r.json()).then(data=>{const box=document.querySelector('#traces');box.replaceChildren();for(const trace of data.records){const details=document.createElement('details');details.className='trace';const summary=document.createElement('summary');summary.textContent=trace.payment_id+' · '+(trace.format_and_citation_check?'格式与引用校验通过':'需人工核查');const pre=document.createElement('pre');pre.textContent='输入提示词\n'+trace.prompt+'\n\n原始回复\n'+trace.raw_response+'\n\n回复 SHA-256\n'+trace.response_sha256;details.append(summary,pre);box.append(details)}}).catch(()=>{document.querySelector('#traces').textContent='记录暂不可用，请使用上方下载文件。'});
